version: "3.9"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: 'admin-tool-ha'
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress     

  wordpress:
    depends_on: 
        - database
    links: 
        - database
    image: wordpress:latest
    restart: always
    read_only: false
    ports: 
        - '8000:80'
    environment:
      DB_HOST: db
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      WP_ENV: development
    volumes: 
        - wordpress_data:/var/www/html:rw
volumes:
  db_data: {}
  wordpress_data: {}
