version: "3.9"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: 'admin-tool-ha'
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress     

  wordpress:
    image: wordpress 
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      WP_ENV: development
      # WP_HOME: http://localhost:8000
      # WP_SITEURL: http://localhost:8000/wp
volumes:
  db_data: {}
  wordpress_data: {}
